### ISSUE TITLE
Add block of code to .zip file

### ISSUE THREAD

**Issue by ElizabethFernandes** [ubc-library-rc/gis-intro-leaflet#16]
At https://ubc-library-rc.github.io/gis-intro-leaflet/content/boilerplate.html it is said that the block of code is available at the .ZIP file (available at https://ubc-library-rc.github.io/gis-intro-leaflet/ ). However, the only documents available at the .ZIP file are: ubcbuilding.js and boilerplate.html

2 very possible options: an attachment is missing OR I have no idea what I'm doing.

**Comment by ect123** [comment]
This could be stemming my unclear description in the text on [the workshop page](https://ubc-library-rc.github.io/gis-intro-leaflet/content/boilerplate.html). The the boilerplate.html is the boilerplate file, but in order to view it as a text html document it needs to be opened in a text/code editor. If the default program for .html files on your machine is your internet browser, then it will just open as a web page. 

If I were to add a comment about needing to open the .html file in a text or code editor like [Atom](https://atom.io/), would it solve this issue?

**Comment by ElizabethFernandes** [comment]
Oh, ok, got it! In order to show the *text*. Because it opens the web page, a map, I got confused. I had to click on it with the right button to see the "view source code" option. I also opened it with atom.
I think it is ok, I will "re-take the workshop" from that part and see how it works!
